### ISSUE TITLE
File Names for Unit Tests

### ISSUE THREAD

**Issue by pfankhauser** [leggedrobotics/styleguide#1]
Relevant section: [File Names](https://leggedrobotics.github.io/styleguide/cppguide.html#File_Names)

I would like to suggest to use CamelCase naming also for unit test files of classes: `MyUsefulClassTest.cpp` instead of `myusefulclass_test.cpp` because it makes it more consistent with the naming of the class `MyUsefulClass.cpp`.

Here's an [example](https://github.com/ethz-asl/grid_map/tree/master/grid_map_core/test).

What's the opinion on this?

**Comment by hogabrie** [comment]
I agree that myusefulclass_test.cpp is inconsistent. But I would reserve CamelCase for classes only. 
Maybe have it for Test fixtures, but not for tests of classes?

What about MyUsefulClass_test.cpp? Then the convention would be "filename" + "_test.cpp".

**Comment by pfankhauser** [comment]
MyUsefulClass_test.cpp sounds good 👍
